Repository Data-cin/projeto-ess, pull requests merged in 2024-06, with the labels that each got.

#16 Display feature
  features/display.feature
Labels: documentation

#13 Feat(Search) added Feature Search
  features/comments.feature
  features/display.feature
  features/maintenance.feature
  features/search.feature
Labels: documentation

#26 PR merge dev
  features/availability.feature
Labels: bug, help wanted

#35 Development/miguel
  backend/src/controllers/posts.js
  backend/src/db/db.js
  backend/src/models/post.js
Labels: bug

#36 Backend boilerplate
  backend/.editorconfig
  backend/.env.example
  backend/.eslintrc
  backend/.gitignore
  backend/.husky/pre-commit
  backend/.husky/pre-push
  backend/.prettierrc
  backend/README.md
  backend/docs/architecture-pattern.md
  backend/jest.config.js
  backend/package-lock.json
  backend/package.json
  backend/setupTests.ts
  backend/src/app.js
  backend/src/app.ts
  backend/src/controllers/controller.js
  backend/src/controllers/posts.js
  backend/src/controllers/test.controller.ts
  backend/src/database/index.ts
  backend/src/db/db.js
  backend/src/di/index.ts
  backend/src/di/injector.ts
  backend/src/entities/base.entity.ts
  backend/src/entities/test.entity.ts
  backend/src/env.ts
  backend/src/index.ts
  backend/src/logger.ts
  backend/src/models/base.model.ts
  backend/src/models/post.js
  backend/src/models/test.model.ts
  backend/src/repositories/base.repository.ts
  backend/src/repositories/other.repository.ts
  backend/src/repositories/test.repository.ts
  backend/src/routes/index.ts
  backend/src/services/test.service.ts
  backend/src/utils/errors/http.error.ts
  backend/src/utils/result.ts
  backend/src/views/router.js
  backend/test/app.test.js
  backend/tests/controllers/test.controller.spec.ts
  backend/tests/controllers/test.steps.ts
  backend/tests/features/tests-service.feature
  backend/tests/features/tests.feature
  backend/tests/services/test.service.spec.ts
  backend/tests/services/test.service.steps.ts
  backend/tests/utils/.gitkeep
  backend/tsconfig.json
Labels: enhancement

#37 Development/miguel
  backend/jest.config.js
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/controllers/posts.js
  backend/src/views/exemplo.routes.js
  backend/src/views/posts.routes.js
  backend/test/app.test.js
  backend/tests/features/post.feature
  backend/tests/post.test.js
Labels: documentation, enhancement, tests

#45 Feat(comment): Adicionado rotas backend e testes bdd
  backend/package-lock.json
  backend/src/app.js
  backend/src/controllers/comment.js
  backend/src/models/comment.js
  backend/src/views/comment.routes.js
  backend/tests/comment.test.js
  backend/tests/features/comment.feature
  features/comments.feature
Labels: enhancement, tests

#54 feat(comment): ajuste de conflito de merge
  backend/src/models/comment.js
  backend/tests/comment.test.js
  backend/tests/search.test.js
Labels: bug

#58 fix: correção dos scenarios para scenarios de serviço
  backend/tests/features/post.feature
  backend/tests/post.test.js
Labels: bug
